spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        profile-view: profile_view_channel
        follower_channel:
          name: follower_channel
        comment_channel:
          name: comment_channel
        fund-raised-event:
          name: fund-raised-channel


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group


server:
  port: 8086

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082
